# Generated by Django 3.2.12 on 2022-03-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('picture', models.CharField(blank=True, max_length=2000)),
                ('total_num', models.IntegerField()),
                ('remain_num', models.IntegerField()),
                ('use_content', models.CharField(blank=True, max_length=2000)),
                ('attention_content', models.CharField(blank=True, max_length=2000)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sm_device',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.CharField(blank=True, max_length=2000)),
                ('remark', models.CharField(blank=True, max_length=2000)),
                ('create_time', models.DateTimeField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.user')),
            ],
            options={
                'db_table': 'sm_report',
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='modify_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modify_user', to='community.user'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_user', to='community.user'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.user'),
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_remark', models.CharField(blank=True, max_length=2000)),
                ('create_time', models.DateTimeField()),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.report')),
            ],
            options={
                'db_table': 'sm_report_review',
            },
        ),
        migrations.CreateModel(
            name='ReceiveRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_num', models.IntegerField()),
                ('status', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.user')),
            ],
            options={
                'db_table': 'sm_receive_record',
            },
        ),
    ]
